"""added Family Group relation on user model

Revision ID: 56688b7dba6f
Revises: 69abd1a75b83
Create Date: 2026-03-15 14:56:49.117947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56688b7dba6f"
down_revision: Union[str, Sequence[str], None] = "69abd1a75b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_family_groups_id"), "family_groups", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_family_groups_id"), "family_groups", type_="unique")
    # ### end Alembic commands ###
