"""added otp tracking

Revision ID: 79a9234549a7
Revises: add8743e7f91
Create Date: 2026-03-07 12:52:13.590150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "79a9234549a7"
down_revision: Union[str, Sequence[str], None] = "add8743e7f91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_trackings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("send_count", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "last_sent",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_otp_trackings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_trackings")),
    )
    op.create_index(
        op.f("ix_otp_trackings_phone_number"),
        "otp_trackings",
        ["phone_number"],
        unique=True,
    )
    op.alter_column(
        "users", "phone_number", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )
    op.alter_column(
        "users", "phone_number", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.drop_index(op.f("ix_otp_trackings_phone_number"), table_name="otp_trackings")
    op.drop_table("otp_trackings")
    # ### end Alembic commands ###
